title: "<p align='center'> Srinath Tummala </p>"
logo: "/assets/img/logo.png"

description: | 
  <p align="center">
    <a href="pdf/Srinath_Tummala_AI_Engineer.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/srinath-tummala/">LinkedIn</a> |
    <a href="https://github.com/SrinathTummala">GitHub</a>
  </p>

  <br>
  ðŸ‘‹ Hi, I'm <strong>Srinath Tummala</strong> â€” an AI Engineer & Data Scientist with 4 years of experience specialising in production-ready <strong>Generative AI, LLMs, and RAG pipelines</strong>.
  </br>
  <br>
  <strong>Core Expertise:</strong>
  <ul>
    <li><strong>GenAI:</strong> RAG pipelines using LangChain, FAISS, and GPT-4.</li>
    <li><strong>Performance:</strong> High-dimensional modelling via SVI.</li>
    <li><strong>Deployment:</strong> FastAPI microservices with Docker and AWS.</li>
  </ul>

  Let's build smarter, scalable AI solutions! ðŸš€ðŸ“ŠðŸ¤–
  <br>
  <small>Hyderabad, India </small>

theme: jekyll-theme-minimal
