title: "<p align='center'> Srinath Tummala </p>"
logo: "/assets/img/logo.png"

description: | 
  <p align="center">
    <a href="pdf/Resume_Srinath.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/srinath-tummala/">LinkedIn</a> |
    <a href="https://github.com/SrinathTummala">GitHub</a>
  </p>
 
  <br>
   Hey there! This is Srinath Tummala, a junior data scientist with over an year of hands-on experience in turning data into actionable insights.ğŸ‘¨â€ğŸ’»ğŸ“ŠğŸ’¡
  </br>

theme: jekyll-theme-minimal
