title: "<p align='center'> Srinath Tummala </p>"
logo: "/assets/img/logo.png"

description: | 
  <p align="center">
    <a href="pdf/Resume_Srinath.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/srinath-tummala/">LinkedIn</a> |
    <a href="https://github.com/SrinathTummala">GitHub</a>
  </p>
 
  <br>
   Hey there! Iâ€™m Srinath Tummala, a passionate and driven data scientist with over three years of hands-on experience in data analysis, machine learning, and statistical modeling. I specialize in extracting actionable insights from complex datasets and have worked on real-world projects in domains like predictive modeling, NLP, and Generative AI. I enjoy blending statistical rigor with creative problem-solving to drive data-powered decisions. ğŸ‘¨â€ğŸ’»ğŸ“ŠğŸ§ 
  </br>

theme: jekyll-theme-minimal
